// Generated by gencpp from file localization_slam/save_map.msg
// DO NOT EDIT!


#ifndef LOCALIZATION_SLAM_MESSAGE_SAVE_MAP_H
#define LOCALIZATION_SLAM_MESSAGE_SAVE_MAP_H

#include <ros/service_traits.h>


#include <localization_slam/save_mapRequest.h>
#include <localization_slam/save_mapResponse.h>


namespace localization_slam
{

struct save_map
{

typedef save_mapRequest Request;
typedef save_mapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct save_map
} // namespace localization_slam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::localization_slam::save_map > {
  static const char* value()
  {
    return "9b82c64d089149d300598523af304f22";
  }

  static const char* value(const ::localization_slam::save_map&) { return value(); }
};

template<>
struct DataType< ::localization_slam::save_map > {
  static const char* value()
  {
    return "localization_slam/save_map";
  }

  static const char* value(const ::localization_slam::save_map&) { return value(); }
};


// service_traits::MD5Sum< ::localization_slam::save_mapRequest> should match
// service_traits::MD5Sum< ::localization_slam::save_map >
template<>
struct MD5Sum< ::localization_slam::save_mapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::localization_slam::save_map >::value();
  }
  static const char* value(const ::localization_slam::save_mapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::localization_slam::save_mapRequest> should match
// service_traits::DataType< ::localization_slam::save_map >
template<>
struct DataType< ::localization_slam::save_mapRequest>
{
  static const char* value()
  {
    return DataType< ::localization_slam::save_map >::value();
  }
  static const char* value(const ::localization_slam::save_mapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::localization_slam::save_mapResponse> should match
// service_traits::MD5Sum< ::localization_slam::save_map >
template<>
struct MD5Sum< ::localization_slam::save_mapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::localization_slam::save_map >::value();
  }
  static const char* value(const ::localization_slam::save_mapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::localization_slam::save_mapResponse> should match
// service_traits::DataType< ::localization_slam::save_map >
template<>
struct DataType< ::localization_slam::save_mapResponse>
{
  static const char* value()
  {
    return DataType< ::localization_slam::save_map >::value();
  }
  static const char* value(const ::localization_slam::save_mapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LOCALIZATION_SLAM_MESSAGE_SAVE_MAP_H
